name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy in EC2
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
            SSH_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
            REMOTE_HOST : ${{ secrets.HOST_NAME }}
            REMOTE_USER : ${{ secrets.USER_NAME }}
            TARGET : ${{ secrets.TARGET_DIR }}
            SCRIPT_AFTER: |
              cd $TARGET
              source ~/miniconda3/etc/profile.d/conda.sh
              conda activate airflow
              pip install -r requirements.txt