name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOST_NAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            TARGET_DIR : ${{ secrets.TARGET_DIR  }}
            
        run: |
          echo "$Personal" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd $TARGET_DIR &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main
          '